import City from "./City";

const cityList: City[] = [
  {
    key: "01JQD4P5HE8QZDE2Q5V6YBKJAY",
    name: "Eucla",
    timeZone: "Australia/Eucla",
    country: "Australia",
  },
  {
    key: "01JQD4P5HE8QZDE2Q5V6YBKJAZ",
    name: "Christmas Island",
    timeZone: "Indian/Christmas",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2E",
    name: "Sydney",
    timeZone: "Australia/Sydney",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2F",
    name: "Melbourne",
    timeZone: "Australia/Melbourne",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2G",
    name: "Brisbane",
    timeZone: "Australia/Brisbane",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2H",
    name: "Perth",
    timeZone: "Australia/Perth",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2I",
    name: "Adelaide",
    timeZone: "Australia/Adelaide",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2J",
    name: "Gold Coast",
    timeZone: "Australia/Brisbane",
    country: "Australia",
  },
  {
    key: "01JQCZFV9XBFV464FQ0Y15DFCR",
    name: "Canberra",
    timeZone: "Australia/Sydney",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2K",
    name: "Beijing",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2L",
    name: "Shanghai",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2M",
    name: "Guangzhou",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2N",
    name: "Shenzhen",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQDADZBH0GWHEK8T01W02Z7T",
    name: "Chongqing",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQDADZBH0GWHEK8T01W02Z7V",
    name: "Chengdu",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQDADZBH0GWHEK8T01W02Z7W",
    name: "Xi'an",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2O",
    name: "Urumqi",
    timeZone: "Asia/Urumqi",
    country: "China",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2P",
    name: "Kashgar",
    timeZone: "Asia/Urumqi",
    country: "China",
  },
  {
    key: "01JQBVK368H82SWQMQ6GXJ7BGJ",
    name: "Jakarta",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQCYTEP5E1STDCW9EPVZPJTN",
    name: "Medan",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQCZ4FSXXWPXQ52YMWRXV6MX",
    name: "Balikpapan",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQCYTEP5E1STDCW9EPVZPJTP",
    name: "Bandung",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQD7J17WABM0RMZ5AVJFHQBG",
    name: "Semarang",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQCYYBH4G1CCDYTMZ2XMMC3Z",
    name: "Yogyakarta",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQCYYBH4G1CCDYTMZ2XMMC41",
    name: "Surabaya",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQD7K5G5NRBV10W2V35C2H78",
    name: "Malang",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQCYYBH4G1CCDYTMZ2XMMC42",
    name: "Denpasar",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQD7MFJ5D2T43FZ05TAN5AY2",
    name: "Banjarbaru",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQD7MFJ5D2T43FZ05TAN5AXS",
    name: "Mataram",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQD7YA1CXEX0FNHRNYERKX87",
    name: "Kupang",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQD7YA1CXEX0FNHRNYERKX88",
    name: "Pulau Komodo",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQD7YA1CXEX0FNHRNYERKX89",
    name: "Manado",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQBVK368H82SWQMQ6GXJ7BGK",
    name: "Makassar",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQBVK368H82SWQMQ6GXJ7BGM",
    name: "Ternate",
    timeZone: "Asia/Jayapura",
    country: "Indonesia",
  },
  {
    key: "01JQCZHXPEYDC5KPSMZZ3NTQAF",
    name: "Pontianak",
    timeZone: "Asia/Pontianak",
    country: "Indonesia",
  },
  {
    key: "01JQCZHXPEYDC5KPSMZZ3NTQAG",
    name: "Singkawang",
    timeZone: "Asia/Pontianak",
    country: "Indonesia",
  },
  {
    key: "01JQCZTXEHCXWQH8AE4527QBFH",
    name: "Samarinda",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQCZ6KVP7KMY3NCD6EQWF1Z0",
    name: "Ambon",
    timeZone: "Asia/Jayapura",
    country: "Indonesia",
  },
  {
    key: "01JQCZ6KVP7KMY3NCD6EQWF1Z1",
    name: "Sorong",
    timeZone: "Asia/Jayapura",
    country: "Indonesia",
  },
  {
    key: "01JQCZ6KVP7KMY3NCD6EQWF1Z2",
    name: "Timika",
    timeZone: "Asia/Jayapura",
    country: "Indonesia",
  },
  {
    key: "01JQBVK368H82SWQMQ6GXJ7BGN",
    name: "Jayapura",
    timeZone: "Asia/Jayapura",
    country: "Indonesia",
  },
  {
    key: "01JQD9X7ED9Q86CED93NC898K0",
    name: "Sumba",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQDAAZ3772M0Z7MYG8VP8FTC",
    name: "Kendari",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQDAAZ3772M0Z7MYG8VP8FTD",
    name: "Palu",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8VW",
    name: "Kuala Lumpur",
    timeZone: "Asia/Kuala_Lumpur",
    country: "Malaysia",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8VX",
    name: "George Town",
    timeZone: "Asia/Kuala_Lumpur",
    country: "Malaysia",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8VY",
    name: "Kuching",
    timeZone: "Asia/Kuching",
    country: "Malaysia",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8VZ",
    name: "Kota Kinabalu",
    timeZone: "Asia/Kuching",
    country: "Malaysia",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8W0",
    name: "Auckland",
    timeZone: "Pacific/Auckland",
    country: "New Zealand",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8W1",
    name: "Wellington",
    timeZone: "Pacific/Auckland",
    country: "New Zealand",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8W2",
    name: "Christchurch",
    timeZone: "Pacific/Auckland",
    country: "New Zealand",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8W3",
    name: "Dunedin",
    timeZone: "Pacific/Auckland",
    country: "New Zealand",
  },
  {
    key: "01JQBZQ023B2ZD09T8RJJMA4NK",
    name: "Singapore",
    timeZone: "Asia/Singapore",
    country: "Singapore",
  },
  {
    key: "01JQDA7YQP6JS0QFDZNCVY04XC",
    name: "Seoul",
    timeZone: "Asia/Seoul",
    country: "South Korea",
  },
  {
    key: "01JQDA7YQP6JS0QFDZNCVY04XD",
    name: "Busan",
    timeZone: "Asia/Seoul",
    country: "South Korea",
  },
  {
    key: "01JQD9X7ED9Q86CED93NC898JW",
    name: "Tokyo",
    timeZone: "Asia/Tokyo",
    country: "Japan",
  },
  {
    key: "01JQD9X7ED9Q86CED93NC898JX",
    name: "Fukuoka",
    timeZone: "Asia/Tokyo",
    country: "Japan",
  },
  {
    key: "01JQD9X7ED9Q86CED93NC898JY",
    name: "Yokohama",
    timeZone: "Asia/Tokyo",
    country: "Japan",
  },
  {
    key: "01JQD9X7ED9Q86CED93NC898JZ",
    name: "	Osaka",
    timeZone: "Asia/Tokyo",
    country: "Japan",
  },
  {
    key: "01JQDADZBH0GWHEK8T01W02Z7R",
    name: "Taipei",
    timeZone: "Asia/Taipei",
    country: "Taiwan",
  },
  {
    key: "01JQBZQJN9AJRPT52D566RX14N",
    name: "Bangkok",
    timeZone: "Asia/Bangkok",
    country: "Thailand",
  },
  {
    key: "01JQCYTEP5E1STDCW9EPVZPJTQ",
    name: "Chiang Mai",
    timeZone: "Asia/Bangkok",
    country: "Thailand",
  },
  {
    key: "01JQBZQJN9AJRPT52D566RX14P",
    name: "Phuket",
    timeZone: "Asia/Bangkok",
    country: "Thailand",
  },
  {
    key: "01JQDANJWDV4P80XCYCYGC26MA",
    name: "Quezon City",
    timeZone: "Asia/Manila",
    country: "Philippines",
  },
  {
    key: "01JQDANJWDV4P80XCYCYGC26MB",
    name: "Manila",
    timeZone: "Asia/Manila",
    country: "Philippines",
  },
  {
    key: "01JQDANJWDV4P80XCYCYGC26MC",
    name: "Davao City",
    timeZone: "Asia/Manila",
    country: "Philippines",
  },
  {
    key: "01JQDANJWDV4P80XCYCYGC26MD",
    name: "Cebu City",
    timeZone: "Asia/Manila",
    country: "Philippines",
  },
  {
    key: "01JQDANJWDV4P80XCYCYGC26ME",
    name: "Makati",
    timeZone: "Asia/Manila",
    country: "Philippines",
  },
  {
    key: "01JQC03NTHZJRY16QBMPJ39XRK",
    name: "London",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQC03NTHZJRY16QBMPJ39XRL",
    name: "Edinburgh",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQCZBB241VXKZQ1YX209RSAX",
    name: "Glasgow",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQC03NTHZJRY16QBMPJ39XRM",
    name: "Belfast",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQCYTEP5E1STDCW9EPVZPJTR",
    name: "Manchester",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQC03NTHZJRY16QBMPJ39XRP",
    name: "Liverpool",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQC03NTHZJRY16QBMPJ39XRQ",
    name: "Birmingham",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQCZCXRX52WC5Y0GWRQ3JVD3",
    name: "Oxford",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQCZCXRX52WC5Y0GWRQ3JVD4",
    name: "Cambridge",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQCZDW31TNMEVBHDFSWQK3FC",
    name: "Paris",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZGPGJKH23357M58MG9J2H",
    name: "Marseille",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZGPGJKH23357M58MG9J2J",
    name: "Lyon",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZGPGJKH23357M58MG9J2K",
    name: "Nice",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZGPGJKH23357M58MG9J2M",
    name: "Bordeaux",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZGPGJKH23357M58MG9J2N",
    name: "Lille",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZHXPEYDC5KPSMZZ3NTQAC",
    name: "Montpellier",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZHXPEYDC5KPSMZZ3NTQAD",
    name: "Rennes",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZHXPEYDC5KPSMZZ3NTQAE",
    name: "Toulouse",
    timeZone: "Europe/Paris",
    country: "France",
  },

  {
    key: "01JQCZYMFWT14T740C2B4SPG8S",
    name: "Berlin",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8T",
    name: "Munich",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8V",
    name: "Hamburg",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8W",
    name: "Cologne",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8X",
    name: "Dortmund",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQD05SYWXA35084GY0X00FJ8",
    name: "Aachen",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8Y",
    name: "Antwerp",
    timeZone: "Europe/Brussels",
    country: "Belgium",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8Z",
    name: "Brussels",
    timeZone: "Europe/Brussels",
    country: "Belgium",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG90",
    name: "Zurich",
    timeZone: "Europe/Zurich",
    country: "Switzerland",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG91",
    name: "Geneva",
    timeZone: "Europe/Zurich",
    country: "Switzerland",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG92",
    name: "Lausanne",
    timeZone: "Europe/Zurich",
    country: "Switzerland",
  },
  {
    key: "01JQD07X3GBKYQZTQ91FQJJ7QN",
    name: "Basel",
    timeZone: "Europe/Zurich",
    country: "Switzerland",
  },
  {
    key: "01JQD1AS2PANV1ZZ30YRYQGJZ8",
    name: "Dublin",
    timeZone: "Europe/Dublin",
    country: "Ireland",
  },
  {
    key: "01JQD1BAV7E1AQHTJ8GA063V9Y",
    name: "Amsterdam",
    timeZone: "Europe/Amsterdam",
    country: "Netherlands",
  },
  {
    key: "01JQD4JGDWH0DZCHERBWJBJYMT",
    name: "Rotterdam",
    timeZone: "Europe/Amsterdam",
    country: "Netherlands",
  },
  {
    key: "01JQD4JGDWH0DZCHERBWJBJYMV",
    name: "Kathmandu",
    timeZone: "Asia/Kathmandu",
    country: "Nepal",
  },
  {
    key: "01JQD4JGDWH0DZCHERBWJBJYMW",
    name: "Pokhara",
    timeZone: "Asia/Kathmandu",
    country: "Nepal",
  },
  {
    key: "01JQD4JGDWH0DZCHERBWJBJYMX",
    name: "Lumbini",
    timeZone: "Asia/Kathmandu",
    country: "Nepal",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4S6",
    name: "New York",
    timeZone: "America/New_York",
    country: "United States",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4S7",
    name: "Los Angeles",
    timeZone: "America/Los_Angeles",
    country: "United States",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4S8",
    name: "Boston",
    timeZone: "America/New_York",
    country: "United States",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4S9",
    name: "San Francisco",
    timeZone: "America/Los_Angeles",
    country: "United States",
  },
  {
    key: "01JQD78QKCE36BSH38W7C56XB9",
    name: "Chicago",
    timeZone: "America/Chicago",
    country: "United States",
  },
  {
    key: "01JQD78QKCE36BSH38W7C56XB8",
    name: "Houston",
    timeZone: "America/Chicago",
    country: "United States",
  },
  {
    key: "01JQD78QKCE36BSH38W7C56XBA",
    name: "Dallas, Texas",
    timeZone: "America/Chicago",
    country: "United States",
  },
  {
    key: "01JQD78QKCE36BSH38W7C56XBB",
    name: "Austin, Texas",
    timeZone: "America/Chicago",
    country: "United States",
  },
  {
    key: "01JQD78QKCE36BSH38W7C56XBC",
    name: "Seattle",
    timeZone: "America/Los_Angeles",
    country: "United States",
  },
  {
    key: "01JQD78QKCE36BSH38W7C56XBD",
    name: "Denver, Colorado",
    timeZone: "America/Denver",
    country: "United States",
  },
  {
    key: "01JQD78QKCE36BSH38W7C56XBE",
    name: "Phoenix, Arizona",
    timeZone: "America/Phoenix",
    country: "United States",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4SA",
    name: "Toronto",
    timeZone: "America/Toronto",
    country: "Canada",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4SB",
    name: "Waterloo",
    timeZone: "America/Toronto",
    country: "Canada",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4SC",
    name: "Victoria, British Columbia",
    timeZone: "America/Vancouver",
    country: "Canada",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4SD",
    name: "Vancouver, British Columbia",
    timeZone: "America/Vancouver",
    country: "Canada",
  },
  {
    key: "01JQD76JYCDP1TPXHTF94DMW4K",
    name: "Montreal",
    timeZone: "America/Toronto",
    country: "Canada",
  },
  {
    key: "01JQD803N9T3476T70ASAHVCCV",
    name: "Ottawa",
    timeZone: "America/Toronto",
    country: "Canada",
  },
];

export default function sortedCityList() {
  return cityList.sort(
    (a, b) =>
      a.country.localeCompare(b.country) || a.name.localeCompare(b.name),
  );
}
