import City from "./City";

const cityList: City[] = [
  {
    key: "01JQD4P5HE8QZDE2Q5V6YBKJAY",
    name: "Eucla",
    timeZone: "Australia/Eucla",
    country: "Australia",
  },
  {
    key: "01JQD4P5HE8QZDE2Q5V6YBKJAZ",
    name: "Christmas Island",
    timeZone: "Indian/Christmas",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2E",
    name: "Sydney",
    timeZone: "Australia/Sydney",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2F",
    name: "Melbourne",
    timeZone: "Australia/Melbourne",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2G",
    name: "Brisbane",
    timeZone: "Australia/Brisbane",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2H",
    name: "Perth",
    timeZone: "Australia/Perth",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2I",
    name: "Adelaide",
    timeZone: "Australia/Adelaide",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2J",
    name: "Gold Coast",
    timeZone: "Australia/Brisbane",
    country: "Australia",
  },
  {
    key: "01JQCZFV9XBFV464FQ0Y15DFCR",
    name: "Canberra",
    timeZone: "Australia/Sydney",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2K",
    name: "Beijing",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2L",
    name: "Shanghai",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2M",
    name: "Guangzhou",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2N",
    name: "Shenzhen",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQDADZBH0GWHEK8T01W02Z7T",
    name: "Chongqing",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQDADZBH0GWHEK8T01W02Z7V",
    name: "Chengdu",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQDADZBH0GWHEK8T01W02Z7W",
    name: "Xi'an",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2O",
    name: "Urumqi",
    timeZone: "Asia/Urumqi",
    country: "China",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2P",
    name: "Kashgar",
    timeZone: "Asia/Urumqi",
    country: "China",
  },
  {
    key: "01JQENQD6FWZ7GWFFCC98D8GRY",
    name: "Xiamen",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQBVK368H82SWQMQ6GXJ7BGJ",
    name: "Jakarta",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMXE2S0CDSE4SMSRS6R7TG",
    name: "Banda Aceh",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMXE2S0CDSE4SMSRS6R7TH",
    name: "Lhokseumawe",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMXE2S0CDSE4SMSRS6R7TJ",
    name: "Meulaboh",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQCYTEP5E1STDCW9EPVZPJTN",
    name: "Medan",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMDZ1GNRDXC7VKRHT2J9MD",
    name: "Balige",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMDZ1GNRDXC7VKRHT2J9ME",
    name: "Tarutung",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMDZ1GNRDXC7VKRHT2J9MF",
    name: "Sibolga",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMWKR0NXE0AFEVFTEN4YX9",
    name: "Pulau Nias",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMH9FVZX5PXW2BQP3A6WRF",
    name: "Padang",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEN0Y6T2VB5E76A80ZA40VE",
    name: "Pulau Mentawai",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMH9FVZX5PXW2BQP3A6WRG",
    name: "Palembang",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMH9FVZX5PXW2BQP3A6X34",
    name: "Bandar Lampung",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQCYTEP5E1STDCW9EPVZPJTP",
    name: "Bandung",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQD7J17WABM0RMZ5AVJFHQBG",
    name: "Semarang",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMKVKQXH52NAW6X7XRWR4Y",
    name: "Surakarta",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMN69XWVGTJFAFCVV8KEAR",
    name: "Madiun",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQCYYBH4G1CCDYTMZ2XMMC3Z",
    name: "Yogyakarta",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQCYYBH4G1CCDYTMZ2XMMC41",
    name: "Surabaya",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMK5AT6HCKCEZT56HGMQGG",
    name: "Sidoarjo",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQD7K5G5NRBV10W2V35C2H78",
    name: "Malang",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMDZ1GNRDXC7VKRHT2J9MG",
    name: "Lumajang",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMDZ1GNRDXC7VKRHT2J9MH",
    name: "Jember",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQEMDZ1GNRDXC7VKRHT2J9MJ",
    name: "Banyuwangi",
    timeZone: "Asia/Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQCYYBH4G1CCDYTMZ2XMMC42",
    name: "Denpasar, Bali",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQCYYBH4G1CCDYTMZ2XMMC43",
    name: "Lovina, Bali",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQCZ4FSXXWPXQ52YMWRXV6MX",
    name: "Balikpapan",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQEN4EVGMH9CRSBH5ZHW7G0F",
    name: "Tarakan",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQD7MFJ5D2T43FZ05TAN5AY2",
    name: "Banjarbaru",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQD7MFJ5D2T43FZ05TAN5AXS",
    name: "Mataram",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQD7YA1CXEX0FNHRNYERKX87",
    name: "Kupang",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQD7YA1CXEX0FNHRNYERKX88",
    name: "Pulau Komodo",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQD7YA1CXEX0FNHRNYERKX89",
    name: "Manado",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQBVK368H82SWQMQ6GXJ7BGK",
    name: "Makassar",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQBVK368H82SWQMQ6GXJ7BGM",
    name: "Ternate",
    timeZone: "Asia/Jayapura",
    country: "Indonesia",
  },
  {
    key: "01JQCZHXPEYDC5KPSMZZ3NTQAF",
    name: "Pontianak",
    timeZone: "Asia/Pontianak",
    country: "Indonesia",
  },
  {
    key: "01JQCZHXPEYDC5KPSMZZ3NTQAG",
    name: "Singkawang",
    timeZone: "Asia/Pontianak",
    country: "Indonesia",
  },
  {
    key: "01JQCZTXEHCXWQH8AE4527QBFH",
    name: "Samarinda",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQCZ6KVP7KMY3NCD6EQWF1Z0",
    name: "Ambon",
    timeZone: "Asia/Jayapura",
    country: "Indonesia",
  },
  {
    key: "01JQCZ6KVP7KMY3NCD6EQWF1Z1",
    name: "Sorong",
    timeZone: "Asia/Jayapura",
    country: "Indonesia",
  },
  {
    key: "01JQCZ6KVP7KMY3NCD6EQWF1Z2",
    name: "Timika",
    timeZone: "Asia/Jayapura",
    country: "Indonesia",
  },
  {
    key: "01JQBVK368H82SWQMQ6GXJ7BGN",
    name: "Jayapura",
    timeZone: "Asia/Jayapura",
    country: "Indonesia",
  },
  {
    key: "01JQD9X7ED9Q86CED93NC898K0",
    name: "Sumba",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQDAAZ3772M0Z7MYG8VP8FTC",
    name: "Kendari",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQDAAZ3772M0Z7MYG8VP8FTD",
    name: "Palu",
    timeZone: "Asia/Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8VW",
    name: "Kuala Lumpur",
    timeZone: "Asia/Kuala_Lumpur",
    country: "Malaysia",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8VX",
    name: "George Town",
    timeZone: "Asia/Kuala_Lumpur",
    country: "Malaysia",
  },
  {
    key: "01JQEN2K8R7HVTM745GBADCMJN",
    name: "Johor Bahru",
    timeZone: "Asia/Kuala_Lumpur",
    country: "Malaysia",
  },
  {
    key: "01JQEN2K8R7HVTM745GBADCMJP",
    name: "Malacca",
    timeZone: "Asia/Kuala_Lumpur",
    country: "Malaysia",
  },
  {
    key: "01JQEN2K8R7HVTM745GBADCMJQ",
    name: "Kota Bharu",
    timeZone: "Asia/Kuala_Lumpur",
    country: "Malaysia",
  },
  {
    key: "01JQEN4EVGMH9CRSBH5ZHW7G0E",
    name: "Kuala Terengganu",
    timeZone: "Asia/Kuala_Lumpur",
    country: "Malaysia",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8VY",
    name: "Kuching",
    timeZone: "Asia/Kuching",
    country: "Malaysia",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8VZ",
    name: "Kota Kinabalu",
    timeZone: "Asia/Kuching",
    country: "Malaysia",
  },
  {
    key: "01JQEN6YNMY10TJ72KWEBVK7VE",
    name: "Bandar Sri Begawan",
    timeZone: "Asia/Brunei",
    country: "Brunei",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8W0",
    name: "Auckland",
    timeZone: "Pacific/Auckland",
    country: "New Zealand",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8W1",
    name: "Wellington",
    timeZone: "Pacific/Auckland",
    country: "New Zealand",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8W2",
    name: "Christchurch",
    timeZone: "Pacific/Auckland",
    country: "New Zealand",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8W3",
    name: "Dunedin",
    timeZone: "Pacific/Auckland",
    country: "New Zealand",
  },
  {
    key: "01JQBZQ023B2ZD09T8RJJMA4NK",
    name: "Singapore",
    timeZone: "Asia/Singapore",
    country: "Singapore",
  },
  {
    key: "01JQDA7YQP6JS0QFDZNCVY04XC",
    name: "Seoul",
    timeZone: "Asia/Seoul",
    country: "South Korea",
  },
  {
    key: "01JQDA7YQP6JS0QFDZNCVY04XD",
    name: "Busan",
    timeZone: "Asia/Seoul",
    country: "South Korea",
  },
  {
    key: "01JQDA7YQP6JS0QFDZNCVY04XE",
    name: "Incheon",
    timeZone: "Asia/Seoul",
    country: "South Korea",
  },
  {
    key: "01JQD9X7ED9Q86CED93NC898JW",
    name: "Tokyo",
    timeZone: "Asia/Tokyo",
    country: "Japan",
  },
  {
    key: "01JQD9X7ED9Q86CED93NC898JX",
    name: "Fukuoka",
    timeZone: "Asia/Tokyo",
    country: "Japan",
  },
  {
    key: "01JQD9X7ED9Q86CED93NC898JY",
    name: "Yokohama",
    timeZone: "Asia/Tokyo",
    country: "Japan",
  },
  {
    key: "01JQD9X7ED9Q86CED93NC898JZ",
    name: "Osaka",
    timeZone: "Asia/Tokyo",
    country: "Japan",
  },
  {
    key: "01JQDADZBH0GWHEK8T01W02Z7R",
    name: "Taipei",
    timeZone: "Asia/Taipei",
    country: "Taiwan",
  },
  {
    key: "01JQDADZBH0GWHEK8T01W02Z7S",
    name: "Hong Kong",
    timeZone: "Asia/Hong_Kong",
    country: "Hong Kong",
  },
  {
    key: "01JQBZQJN9AJRPT52D566RX14N",
    name: "Bangkok",
    timeZone: "Asia/Bangkok",
    country: "Thailand",
  },
  {
    key: "01JQCYTEP5E1STDCW9EPVZPJTQ",
    name: "Chiang Mai",
    timeZone: "Asia/Bangkok",
    country: "Thailand",
  },
  {
    key: "01JQBZQJN9AJRPT52D566RX14P",
    name: "Phuket",
    timeZone: "Asia/Bangkok",
    country: "Thailand",
  },
  {
    key: "01JQDANJWDV4P80XCYCYGC26MA",
    name: "Quezon City",
    timeZone: "Asia/Manila",
    country: "Philippines",
  },
  {
    key: "01JQDANJWDV4P80XCYCYGC26MB",
    name: "Manila",
    timeZone: "Asia/Manila",
    country: "Philippines",
  },
  {
    key: "01JQDANJWDV4P80XCYCYGC26MC",
    name: "Davao City",
    timeZone: "Asia/Manila",
    country: "Philippines",
  },
  {
    key: "01JQDANJWDV4P80XCYCYGC26MD",
    name: "Cebu City",
    timeZone: "Asia/Manila",
    country: "Philippines",
  },
  {
    key: "01JQDANJWDV4P80XCYCYGC26ME",
    name: "Makati",
    timeZone: "Asia/Manila",
    country: "Philippines",
  },
  {
    key: "01JQENBZYS75BJNX9NNE9PTJET",
    name: "Hanoi",
    timeZone: "Asia/Bangkok",
    country: "Vietnam",
  },
  {
    key: "01JQENBZYS75BJNX9NNE9PTJEV",
    name: "Ho Chi Minh",
    timeZone: "Asia/Ho_Chi_Minh",
    country: "Vietnam",
  },
  {
    key: "01JQENBZYS75BJNX9NNE9PTJEW",
    name: "Da Lat",
    timeZone: "Asia/Ho_Chi_Minh",
    country: "Vietnam",
  },
  {
    key: "01JQC03NTHZJRY16QBMPJ39XRK",
    name: "London",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQC03NTHZJRY16QBMPJ39XRL",
    name: "Edinburgh",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQCZBB241VXKZQ1YX209RSAX",
    name: "Glasgow",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQC03NTHZJRY16QBMPJ39XRM",
    name: "Belfast",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQCYTEP5E1STDCW9EPVZPJTR",
    name: "Manchester",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQC03NTHZJRY16QBMPJ39XRP",
    name: "Liverpool",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQC03NTHZJRY16QBMPJ39XRQ",
    name: "Birmingham",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQCZCXRX52WC5Y0GWRQ3JVD3",
    name: "Oxford",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQCZCXRX52WC5Y0GWRQ3JVD4",
    name: "Cambridge",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQCZDW31TNMEVBHDFSWQK3FC",
    name: "Paris",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZGPGJKH23357M58MG9J2H",
    name: "Marseille",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZGPGJKH23357M58MG9J2J",
    name: "Lyon",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZGPGJKH23357M58MG9J2K",
    name: "Nice",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZGPGJKH23357M58MG9J2M",
    name: "Bordeaux",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZGPGJKH23357M58MG9J2N",
    name: "Lille",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZHXPEYDC5KPSMZZ3NTQAC",
    name: "Montpellier",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZHXPEYDC5KPSMZZ3NTQAD",
    name: "Rennes",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZHXPEYDC5KPSMZZ3NTQAE",
    name: "Toulouse",
    timeZone: "Europe/Paris",
    country: "France",
  },

  {
    key: "01JQCZYMFWT14T740C2B4SPG8S",
    name: "Berlin",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8T",
    name: "Munich",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8V",
    name: "Hamburg",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8W",
    name: "Cologne",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8X",
    name: "Dortmund",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQD05SYWXA35084GY0X00FJ8",
    name: "Aachen",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8Y",
    name: "Antwerp",
    timeZone: "Europe/Brussels",
    country: "Belgium",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8Z",
    name: "Brussels",
    timeZone: "Europe/Brussels",
    country: "Belgium",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG90",
    name: "Zurich",
    timeZone: "Europe/Zurich",
    country: "Switzerland",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG91",
    name: "Geneva",
    timeZone: "Europe/Zurich",
    country: "Switzerland",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG92",
    name: "Lausanne",
    timeZone: "Europe/Zurich",
    country: "Switzerland",
  },
  {
    key: "01JQD07X3GBKYQZTQ91FQJJ7QN",
    name: "Basel",
    timeZone: "Europe/Zurich",
    country: "Switzerland",
  },
  {
    key: "01JQEJ4AM4TVE6EDKMYZYMNXX9",
    name: "Bern",
    timeZone: "Europe/Zurich",
    country: "Switzerland",
  },
  {
    key: "01JQD1AS2PANV1ZZ30YRYQGJZ8",
    name: "Dublin",
    timeZone: "Europe/Dublin",
    country: "Ireland",
  },
  {
    key: "01JQD1BAV7E1AQHTJ8GA063V9Y",
    name: "Amsterdam",
    timeZone: "Europe/Amsterdam",
    country: "Netherlands",
  },
  {
    key: "01JQD4JGDWH0DZCHERBWJBJYMT",
    name: "Rotterdam",
    timeZone: "Europe/Amsterdam",
    country: "Netherlands",
  },
  {
    key: "01JQEJ4AM4TVE6EDKMYZYMNXWZ",
    name: "Madrid",
    timeZone: "Europe/Madrid",
    country: "Spain",
  },
  {
    key: "01JQEJ4AM4TVE6EDKMYZYMNXX0",
    name: "Barcelona",
    timeZone: "Europe/Madrid",
    country: "Spain",
  },
  {
    key: "01JQEJ4AM4TVE6EDKMYZYMNXX1",
    name: "Lisbon",
    timeZone: "Europe/Lisbon",
    country: "Portugal",
  },
  {
    key: "01JQEJ4AM4TVE6EDKMYZYMNXX2",
    name: "Porto",
    timeZone: "Europe/Lisbon",
    country: "Portugal",
  },
  {
    key: "01JQEJ4AM4TVE6EDKMYZYMNXX3",
    name: "Rome",
    timeZone: "Europe/Rome",
    country: "Italy",
  },
  {
    key: "01JQEJ4AM4TVE6EDKMYZYMNXX4",
    name: "Milan",
    timeZone: "Europe/Rome",
    country: "Italy",
  },
  {
    key: "01JQEJ4AM4TVE6EDKMYZYMNXX5",
    name: "Turin",
    timeZone: "Europe/Rome",
    country: "Italy",
  },
  {
    key: "01JQEJ4AM4TVE6EDKMYZYMNXX6",
    name: "Sicily",
    timeZone: "Europe/Rome",
    country: "Italy",
  },
  {
    key: "01JQEKXCN77BS1FVBKFS7EAC33",
    name: "Vatican City",
    timeZone: "Europe/Vatican",
    country: "Vatican City",
  },
  {
    key: "01JQEKXCN77BS1FVBKFS7EAC77",
    name: "Vienna",
    timeZone: "Europe/Vienna",
    country: "Austria",
  },
  {
    key: "01JQEKZSGQKPK2JD1FT3XC44YG",
    name: "Innsbruck",
    timeZone: "Europe/Vienna",
    country: "Austria",
  },
  {
    key: "01JQEKXCN77BS1FVBKFS7EAC78",
    name: "Budapest",
    timeZone: "Europe/Budapest",
    country: "Hungary",
  },
  {
    key: "01JQEKXCN77BS1FVBKFS7EAC79",
    name: "Prague",
    timeZone: "Europe/Prague",
    country: "Czech Republic",
  },
  {
    key: "01JQEKZSGQKPK2JD1FT3XC44YH",
    name: "Zagreb",
    timeZone: "Europe/Zagreb",
    country: "Croatia",
  },
  {
    key: "01JQEM2C3KA6PJY6X85DNTDH81",
    name: "Brno",
    timeZone: "Europe/Prague",
    country: "Czech Republic",
  },
  {
    key: "01JQEM2C3KA6PJY6X85DNTDH82",
    name: "Warsaw",
    timeZone: "Europe/Warsaw",
    country: "Poland",
  },
  {
    key: "01JQEM2C3KA6PJY6X85DNTDH83",
    name: "Szczecin",
    timeZone: "Europe/Warsaw",
    country: "Poland",
  },
  {
    key: "01JQEM2C3KA6PJY6X85DNTDH84",
    name: "Krakow",
    timeZone: "Europe/Warsaw",
    country: "Poland",
  },
  {
    key: "01JQEM2C3KA6PJY6X85DNTDH85",
    name: "Wroclaw",
    timeZone: "Europe/Warsaw",
    country: "Poland",
  },
  {
    key: "01JQEM2C3KA6PJY6X85DNTDH86",
    name: "Copenhagen",
    timeZone: "Europe/Copenhagen",
    country: "Denmark",
  },
  {
    key: "01JQEM2C3KA6PJY6X85DNTDH87",
    name: "Oslo",
    timeZone: "Europe/Oslo",
    country: "Norway",
  },
  {
    key: "01JQEM2C3KA6PJY6X85DNTDH88",
    name: "Bergen",
    timeZone: "Europe/Oslo",
    country: "Norway",
  },
  {
    key: "01JQEM2C3KA6PJY6X85DNTDH89",
    name: "Stockholm",
    timeZone: "Europe/Stockholm",
    country: "Sweden",
  },
  {
    key: "01JQEM9VBVZXR4BJJDT0X56C80",
    name: "Gothenburg",
    timeZone: "Europe/Stockholm",
    country: "Sweden",
  },
  {
    key: "01JQEM9VBVZXR4BJJDT0X56C81",
    name: "Helsinki",
    timeZone: "Europe/Helsinki",
    country: "Finland",
  },
  {
    key: "01JQEM9VBVZXR4BJJDT0X56C82",
    name: "Oulu",
    timeZone: "Europe/Helsinki",
    country: "Finland",
  },
  {
    key: "01JQENF5VTBM2KET2ZVVB7NKWG",
    name: "Delhi",
    timeZone: "Asia/Kolkata",
    country: "India",
  },
  {
    key: "01JQENF5VTBM2KET2ZVVB7NKWH",
    name: "Kolkata",
    timeZone: "Asia/Kolkata",
    country: "India",
  },
  {
    key: "01JQENF5VTBM2KET2ZVVB7NKWJ",
    name: "Bangalore",
    timeZone: "Asia/Kolkata",
    country: "India",
  },
  {
    key: "01JQENF5VTBM2KET2ZVVB7NKWK",
    name: "Hyderabad",
    timeZone: "Asia/Kolkata",
    country: "India",
  },
  {
    key: "01JQENF5VTBM2KET2ZVVB7NKWM",
    name: "Mumbai",
    timeZone: "Asia/Kolkata",
    country: "India",
  },
  {
    key: "01JQD4JGDWH0DZCHERBWJBJYMV",
    name: "Kathmandu",
    timeZone: "Asia/Kathmandu",
    country: "Nepal",
  },
  {
    key: "01JQD4JGDWH0DZCHERBWJBJYMW",
    name: "Pokhara",
    timeZone: "Asia/Kathmandu",
    country: "Nepal",
  },
  {
    key: "01JQD4JGDWH0DZCHERBWJBJYMX",
    name: "Lumbini",
    timeZone: "Asia/Kathmandu",
    country: "Nepal",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4S6",
    name: "New York",
    timeZone: "America/New_York",
    country: "United States",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4S7",
    name: "Los Angeles",
    timeZone: "America/Los_Angeles",
    country: "United States",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4S8",
    name: "Boston",
    timeZone: "America/New_York",
    country: "United States",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4S9",
    name: "San Francisco",
    timeZone: "America/Los_Angeles",
    country: "United States",
  },
  {
    key: "01JQD78QKCE36BSH38W7C56XB9",
    name: "Chicago",
    timeZone: "America/Chicago",
    country: "United States",
  },
  {
    key: "01JQD78QKCE36BSH38W7C56XB8",
    name: "Houston",
    timeZone: "America/Chicago",
    country: "United States",
  },
  {
    key: "01JQD78QKCE36BSH38W7C56XBA",
    name: "Dallas, Texas",
    timeZone: "America/Chicago",
    country: "United States",
  },
  {
    key: "01JQD78QKCE36BSH38W7C56XBB",
    name: "Austin, Texas",
    timeZone: "America/Chicago",
    country: "United States",
  },
  {
    key: "01JQD78QKCE36BSH38W7C56XBC",
    name: "Seattle",
    timeZone: "America/Los_Angeles",
    country: "United States",
  },
  {
    key: "01JQD78QKCE36BSH38W7C56XBD",
    name: "Denver, Colorado",
    timeZone: "America/Denver",
    country: "United States",
  },
  {
    key: "01JQD78QKCE36BSH38W7C56XBE",
    name: "Phoenix, Arizona",
    timeZone: "America/Phoenix",
    country: "United States",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4SA",
    name: "Toronto",
    timeZone: "America/Toronto",
    country: "Canada",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4SB",
    name: "Waterloo",
    timeZone: "America/Toronto",
    country: "Canada",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4SC",
    name: "Victoria, British Columbia",
    timeZone: "America/Vancouver",
    country: "Canada",
  },
  {
    key: "01JQD6XNKT2YD5VP53VM1KH4SD",
    name: "Vancouver, British Columbia",
    timeZone: "America/Vancouver",
    country: "Canada",
  },
  {
    key: "01JQD76JYCDP1TPXHTF94DMW4K",
    name: "Montreal",
    timeZone: "America/Toronto",
    country: "Canada",
  },
  {
    key: "01JQD803N9T3476T70ASAHVCCV",
    name: "Ottawa",
    timeZone: "America/Toronto",
    country: "Canada",
  },
  {
    key: "01JQEHWRKKV2B634FXB7V14A0E",
    name: "Mexico City",
    timeZone: "America/Mexico_City",
    country: "Mexico",
  },
  {
    key: "01JQEHWRKKV2B634FXB7V14A0F",
    name: "Guadalajara",
    timeZone: "America/Mexico_City",
    country: "Mexico",
  },
  {
    key: "01JQEHWRKKV2B634FXB7V14A0G",
    name: "Tijuana",
    timeZone: "America/Tijuana",
    country: "Mexico",
  },
  {
    key: "01JQEHWRKKV2B634FXB7V14A0H",
    name: "Mérida",
    timeZone: "America/Merida",
    country: "Mexico",
  },
  {
    key: "01JQEHWRKKV2B634FXB7V14A0L",
    name: "Monterrey",
    timeZone: "America/Monterrey",
    country: "Mexico",
  },
  {
    key: "01JQEKDDHFM9DTJVANSM1YSX8Q",
    name: "Brasilia",
    timeZone: "America/Sao_Paulo",
    country: "Brazil",
  },
  {
    key: "01JQEKDDHFM9DTJVANSM1YSX8R",
    name: "Sao Paulo",
    timeZone: "America/Sao_Paulo",
    country: "Brazil",
  },
  {
    key: "01JQEKDDHFM9DTJVANSM1YSX8R",
    name: "Rio de Janeiro",
    timeZone: "America/Sao_Paulo",
    country: "Brazil",
  },
  {
    key: "01JQEKDDHFM9DTJVANSM1YSX8S",
    name: "Manaus",
    timeZone: "America/Manaus",
    country: "Brazil",
  },
  {
    key: "01JQEKDDHFM9DTJVANSM1YSX8T",
    name: "Salvador",
    timeZone: "America/Bahia",
    country: "Brazil",
  },
  {
    key: "01JQEKDDHFM9DTJVANSM1YSX8V",
    name: "Fortaleza",
    timeZone: "America/Fortaleza",
    country: "Brazil",
  },
  {
    key: "01JQEKDDHFM9DTJVANSM1YSX8W",
    name: "Recife",
    timeZone: "America/Recife",
    country: "Brazil",
  },
  {
    key: "01JQEKPTYBK26290E7A72HHE4S",
    name: "Cordoba",
    timeZone: "America/Argentina/Cordoba",
    country: "Argentina",
  },
  {
    key: "01JQEKR46G6J92MEKD854QCT09",
    name: "Buenos Aires",
    timeZone: "America/Argentina/Buenos_Aires",
    country: "Argentina",
  },
  {
    key: "01JQEKR46G6J92MEKD854QCT0A",
    name: "Montevideo",
    timeZone: "America/Montevideo",
    country: "Uruguay",
  },
  {
    key: "01JQEKR46G6J92MEKD854QCT0B",
    name: "Asunción",
    timeZone: "America/Asuncion",
    country: "Paraguay",
  },
  {
    key: "01JQEKR46G6J92MEKD854QCT0C",
    name: "Santiago",
    timeZone: "America/Santiago",
    country: "Chile",
  },
  {
    key: "01JQEKR46G6J92MEKD854QCT0D",
    name: "Lima",
    timeZone: "America/Lima",
    country: "Peru",
  },
  {
    key: "01JQEKR46G6J92MEKD854QCT0E",
    name: "Bogotá",
    timeZone: "America/Bogota",
    country: "Colombia",
  },
];

export default function sortedCityList() {
  return cityList.sort(
    (a, b) =>
      a.country.localeCompare(b.country) || a.name.localeCompare(b.name),
  );
}
