import City from "./City";

const cityList: City[] = [
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2E",
    name: "Sydney",
    timeZone: "Australia/Sydney",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2F",
    name: "Melbourne",
    timeZone: "Australia/Melbourne",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2G",
    name: "Brisbane",
    timeZone: "Australia/Brisbane",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2H",
    name: "Perth",
    timeZone: "Australia/Perth",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2I",
    name: "Adelaide",
    timeZone: "Australia/Adelaide",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2J",
    name: "Gold Coast",
    timeZone: "Australia/Brisbane",
    country: "Australia",
  },
  {
    key: "01JQCZFV9XBFV464FQ0Y15DFCR",
    name: "Canberra",
    timeZone: "Australia/Sydney",
    country: "Australia",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2K",
    name: "Beijing",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2L",
    name: "Shanghai",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2M",
    name: "Guangzhou",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2N",
    name: "Shenzhen",
    timeZone: "Asia/Shanghai",
    country: "China",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2O",
    name: "Urumqi",
    timeZone: "Asia/Urumqi",
    country: "China",
  },
  {
    key: "01JQBZHTMB9E07WRPX7TQVBE2P",
    name: "Kashgar",
    timeZone: "Asia/Urumqi",
    country: "China",
  },
  {
    key: "01JQBVK368H82SWQMQ6GXJ7BGJ",
    timeZone: "Asia/Jakarta",
    name: "Jakarta",
    country: "Indonesia",
  },
  {
    key: "01JQCYTEP5E1STDCW9EPVZPJTN",
    timeZone: "Asia/Jakarta",
    name: "Medan",
    country: "Indonesia",
  },
  {
    key: "01JQCZ4FSXXWPXQ52YMWRXV6MX",
    timeZone: "Asia/Makassar",
    name: "Balikpapan",
    country: "Indonesia",
  },
  {
    key: "01JQCYTEP5E1STDCW9EPVZPJTP",
    timeZone: "Asia/Jakarta",
    name: "Bandung",
    country: "Indonesia",
  },
  {
    key: "01JQCYYBH4G1CCDYTMZ2XMMC3Z",
    timeZone: "Asia/Jakarta",
    name: "Yogyakarta",
    country: "Indonesia",
  },
  {
    key: "01JQCYYBH4G1CCDYTMZ2XMMC41",
    timeZone: "Asia/Jakarta",
    name: "Surabaya",
    country: "Indonesia",
  },
  {
    key: "01JQCYYBH4G1CCDYTMZ2XMMC42",
    timeZone: "Asia/Makassar",
    name: "Denpasar",
    country: "Indonesia",
  },
  {
    key: "01JQCYYBH4G1CCDYTMZ2XMMC42",
    timeZone: "Asia/Makassar",
    name: "Manado",
    country: "Indonesia",
  },
  {
    key: "01JQBVK368H82SWQMQ6GXJ7BGK",
    timeZone: "Asia/Makassar",
    name: "Makassar",
    country: "Indonesia",
  },
  {
    key: "01JQBVK368H82SWQMQ6GXJ7BGM",
    timeZone: "Asia/Jayapura",
    name: "Ternate",
    country: "Indonesia",
  },
  {
    key: "01JQCZHXPEYDC5KPSMZZ3NTQAF",
    timeZone: "Asia/Pontianak",
    name: "Pontianak",
    country: "Indonesia",
  },
  {
    key: "01JQCZHXPEYDC5KPSMZZ3NTQAG",
    timeZone: "Asia/Pontianak",
    name: "Singkawang",
    country: "Indonesia",
  },
  {
    key: "01JQCZTXEHCXWQH8AE4527QBFH",
    timeZone: "Asia/Makassar",
    name: "Samarinda",
    country: "Indonesia",
  },
  {
    key: "01JQCZ6KVP7KMY3NCD6EQWF1Z0",
    timeZone: "Asia/Jayapura",
    name: "Ambon",
    country: "Indonesia",
  },
  {
    key: "01JQCZ6KVP7KMY3NCD6EQWF1Z1",
    timeZone: "Asia/Jayapura",
    name: "Sorong",
    country: "Indonesia",
  },
  {
    key: "01JQCZ6KVP7KMY3NCD6EQWF1Z2",
    timeZone: "Asia/Jayapura",
    name: "Timika",
    country: "Indonesia",
  },
  {
    key: "01JQBVK368H82SWQMQ6GXJ7BGN",
    timeZone: "Asia/Jayapura",
    name: "Jayapura",
    country: "Indonesia",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8VW",
    name: "Kuala Lumpur",
    timeZone: "Asia/Kuala_Lumpur",
    country: "Malaysia",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8VX",
    name: "George Town",
    timeZone: "Asia/Kuala_Lumpur",
    country: "Malaysia",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8VY",
    name: "Kuching",
    timeZone: "Asia/Kuching",
    country: "Malaysia",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8VZ",
    name: "Kota Kinabalu",
    timeZone: "Asia/Kuching",
    country: "Malaysia",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8W0",
    name: "Auckland",
    timeZone: "Pacific/Auckland",
    country: "New Zealand",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8W1",
    name: "Wellington",
    timeZone: "Pacific/Auckland",
    country: "New Zealand",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8W2",
    name: "Christchurch",
    timeZone: "Pacific/Auckland",
    country: "New Zealand",
  },
  {
    key: "01JQBZC2RM5K9RF5JV253KA8W3",
    name: "Dunedin",
    timeZone: "Pacific/Auckland",
    country: "New Zealand",
  },
  {
    key: "01JQBZQ023B2ZD09T8RJJMA4NK",
    name: "Singapore",
    timeZone: "Asia/Singapore",
    country: "Singapore",
  },
  {
    key: "01JQBZQJN9AJRPT52D566RX14K",
    name: "Seoul",
    timeZone: "Asia/Seoul",
    country: "South Korea",
  },
  {
    key: "01JQBZQJN9AJRPT52D566RX14N",
    name: "Bangkok",
    timeZone: "Asia/Bangkok",
    country: "Thailand",
  },
  {
    key: "01JQCYTEP5E1STDCW9EPVZPJTQ",
    name: "Chiang Mai",
    timeZone: "Asia/Bangkok",
    country: "Thailand",
  },
  {
    key: "01JQBZQJN9AJRPT52D566RX14P",
    name: "Phuket",
    timeZone: "Asia/Bangkok",
    country: "Thailand",
  },
  {
    key: "01JQC03NTHZJRY16QBMPJ39XRK",
    name: "London",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQC03NTHZJRY16QBMPJ39XRL",
    name: "Edinburgh",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQCZBB241VXKZQ1YX209RSAX",
    name: "Glasgow",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQC03NTHZJRY16QBMPJ39XRM",
    name: "Belfast",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQCYTEP5E1STDCW9EPVZPJTR",
    name: "Manchester",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQC03NTHZJRY16QBMPJ39XRP",
    name: "Liverpool",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQC03NTHZJRY16QBMPJ39XRQ",
    name: "Birmingham",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQCZCXRX52WC5Y0GWRQ3JVD3",
    name: "Oxford",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQCZCXRX52WC5Y0GWRQ3JVD4",
    name: "Cambridge",
    timeZone: "Europe/London",
    country: "United Kingdom",
  },
  {
    key: "01JQCZDW31TNMEVBHDFSWQK3FC",
    name: "Paris",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZGPGJKH23357M58MG9J2H",
    name: "Marseille",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZGPGJKH23357M58MG9J2J",
    name: "Lyon",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZGPGJKH23357M58MG9J2K",
    name: "Nice",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZGPGJKH23357M58MG9J2M",
    name: "Bordeaux",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZGPGJKH23357M58MG9J2N",
    name: "Lille",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZHXPEYDC5KPSMZZ3NTQAC",
    name: "Montpellier",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZHXPEYDC5KPSMZZ3NTQAD",
    name: "Rennes",
    timeZone: "Europe/Paris",
    country: "France",
  },
  {
    key: "01JQCZHXPEYDC5KPSMZZ3NTQAE",
    name: "Toulouse",
    timeZone: "Europe/Paris",
    country: "France",
  },

  {
    key: "01JQCZYMFWT14T740C2B4SPG8S",
    name: "Berlin",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8T",
    name: "Munich",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8V",
    name: "Hamburg",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8W",
    name: "Cologne",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8X",
    name: "Dortmund",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQD05SYWXA35084GY0X00FJ8",
    name: "Aachen",
    timeZone: "Europe/Berlin",
    country: "Germany",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8Y",
    name: "Antwerp",
    timeZone: "Europe/Brussels",
    country: "Belgium",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG8Z",
    name: "Brussels",
    timeZone: "Europe/Brussels",
    country: "Belgium",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG90",
    name: "Zurich",
    timeZone: "Europe/Zurich",
    country: "Switzerland",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG91",
    name: "Geneva",
    timeZone: "Europe/Zurich",
    country: "Switzerland",
  },
  {
    key: "01JQCZYMFWT14T740C2B4SPG92",
    name: "Lausanne",
    timeZone: "Europe/Zurich",
    country: "Switzerland",
  },
  {
    key: "01JQD07X3GBKYQZTQ91FQJJ7QN",
    name: "Basel",
    timeZone: "Europe/Zurich",
    country: "Switzerland",
  },
  {
    key: "01JQD1AS2PANV1ZZ30YRYQGJZ8",
    name: "Dublin",
    timeZone: "Europe/Dublin",
    country: "Ireland",
  },
  {
    key: "01JQD1BAV7E1AQHTJ8GA063V9Y",
    name: "Amsterdam",
    timeZone: "Europe/Amsterdam",
    country: "Netherlands",
  },
  {
    key: "01JQD4JGDWH0DZCHERBWJBJYMT",
    name: "Rotterdam",
    timeZone: "Europe/Amsterdam",
    country: "Netherlands",
  },
  {
    key: "01JQD4JGDWH0DZCHERBWJBJYMV",
    name: "Kathmandu",
    timeZone: "Asia/Kathmandu",
    country: "Nepal",
  },
  {
    key: "01JQD4JGDWH0DZCHERBWJBJYMW",
    name: "Pokhara",
    timeZone: "Asia/Kathmandu",
    country: "Nepal",
  },
  {
    key: "01JQD4JGDWH0DZCHERBWJBJYMX",
    name: "Lumbini",
    timeZone: "Asia/Kathmandu",
    country: "Nepal",
  },
  {
    key: "01JQD4P5HE8QZDE2Q5V6YBKJAY",
    name: "Eucla",
    timeZone: "Australia/Eucla",
    country: "Australia",
  },
  {
    key: "01JQD4P5HE8QZDE2Q5V6YBKJAZ",
    name: "Christmas Island",
    timeZone: "Indian/Christmas",
    country: "Australia",
  },
];

export default function sortedCityList() {
  return cityList.sort(
    (a, b) =>
      a.country.localeCompare(b.country) || a.name.localeCompare(b.name),
  );
}
