/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AgeCalculatorImport } from './routes/age-calculator'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const AgeCalculatorRoute = AgeCalculatorImport.update({
  id: '/age-calculator',
  path: '/age-calculator',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/age-calculator': {
      id: '/age-calculator'
      path: '/age-calculator'
      fullPath: '/age-calculator'
      preLoaderRoute: typeof AgeCalculatorImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/age-calculator': typeof AgeCalculatorRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/age-calculator': typeof AgeCalculatorRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/age-calculator': typeof AgeCalculatorRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/age-calculator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/age-calculator'
  id: '__root__' | '/' | '/age-calculator'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgeCalculatorRoute: typeof AgeCalculatorRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgeCalculatorRoute: AgeCalculatorRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/age-calculator"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/age-calculator": {
      "filePath": "age-calculator.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
